name: Deploy Application

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install npm Dependencies
        run: |
          npm install # Install all dependencies from package.json
          npm install mongodb # Explicitly install mongodb in case it's not listed in package.json

      - name: Export MongoDB Data
        run: node database/mongo/export-mongo.mjs

      - name: Export Postgres Data
        run: node database/postgres/export-postgres.mjs
